<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2EmailService\Module'        => __DIR__ . '/Module.php',
    'Zf2EmailService\Service\Email' => __DIR__ . '/src/Service/Email.php',
    'Zf2EmailService\Factory\TransportFactory' => __DIR__ . '/src/Factory/TransportFactory.php'
);
